#version: '3.6'

#######################################################
#####                    NETWORK                  #####
#######################################################
networks:

################# NETWORK TO PRIVATE SERVERS - BRIDGE TO NETWORK net_srv_public on border commposer ambient
  net_srv_private:
    name: border_net_srv_private # this line is necessary to make a bridge
    external: true # this line is necessary to make a bridge
    enable_ipv6: false
    driver: ${DOCKER_NETWORK_SRV_PRIVATE_DRIVER_MODE}
    internal: false
    driver_opts:
      #parent: ${DOCKER_NETWORK_SRV_PRIVATE_PARENT_INTERFACE}
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      #com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SRV_PRIVATE_SUBNET_IPV4}
          gateway: ${DOCKER_NETWORK_SRV_PRIVATE_GATEWAY_IPV4}


################# NETWORK TO BACKEND COMMUNICATIONS
  net_backend:
    enable_ipv6: false
    driver: ${DOCKER_NETWORK_BACKEND_DRIVER_MODE}
    internal: true
    driver_opts:
      #parent: ${DOCKER_NETWORK_BACKEND_PARENT_INTERFACE}
      com.docker.network.bridge.enable_icc: "true"
        #com.docker.network.bridge.enable_ip_masquerade: "true"
        #com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_BACKEND_SUBNET_IPV4}
        # gateway: ${DOCKER_NETWORK_BACKEND_GATEWAY_IPV4}




#######################################################
#####                   VOLUMES                   #####
#######################################################

volumes:

# certbot(volume) ############################################
  certbot_etc_supervisor:
  certbot_srv_config:
  certbot_var_log:
  certbot_var_spool_cron:
  certbot_usr_local_bin:
  certbot_root:
  #wordpress_var_www:
  #certbot_etc_letsencrypt:

# nextcloud(volume) ############################################
  nextcloud_var_www_html:
  nextcloud_var_www_html_custom_apps:
  nextcloud_var_www_html_config:
  nextcloud_var_www_html_themes:
  #nextcloud_var_www_html_data:

  
# mariadb_nextcloud(volume) ############################################
  mariadb_nextcloud_var_lib_mysql:
  mariadb_nextcloud_root:
  mariadb_nextcloud_etc_supervisor:
  mariadb_nextcloud_usr_local_bin:
  mariadb_nextcloud_etc_mysql:
  mariadb_nextcloud_var_log:
  mariadb_nextcloud_var_spool_cron:

    
#######################################################
#####                   SERVICES                  #####
#######################################################

services:

# portainer(service) ############################################
  portainer:
    container_name: portainer
    hostname: portainer
    build:
      context: ${IMAGE_ROOT_PATH}/portainer
    restart: always
    volumes:
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/portainer/data/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
      #- /etc/letsencrypt:/etc/letsencrypt:ro
      - ${STORAGE_ROOT_PATH}/generic/certbot/etc/letsencrypt/:/etc/letsencrypt:ro
    #ports:
    #  - "9000:9000/tcp" # HTTP
    #  - "9443:9443/tcp" # HTTPS
    networks:
      net_srv_private:
        ipv4_address: ${PORTAINER_DOCKER_NETWORK_SRV_PRIVATE_IPV4}

          
# certbot(service) ############################################
  certbot:
    container_name: certbot
    hostname: certbot
    build:
      context: ${IMAGE_ROOT_PATH}/certbot
    restart: always
    volumes:
      - certbot_etc_supervisor:/etc/supervisor/
      - certbot_srv_config:/srv/config
      - certbot_var_log:/var/log
      - certbot_var_spool_cron:/var/spool/cron
      - certbot_usr_local_bin:/usr/local/bin
      - certbot_root:/root
      #- wordpress_var_www:/var/www/
      #- ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/workspace/var/www/:/var/www/
      - ${STORAGE_ROOT_PATH}/generic/certbot/etc/letsencrypt/:/etc/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      net_srv_private:
        ipv4_address: ${CERTBOT_DOCKER_NETWORK_SRV_PRIVATE_IPV4}

# nextcloud(service) ############################################
  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    #image: nextcloud:stable
    build:
      context: ${IMAGE_ROOT_PATH}/nextcloud
    restart: always
    depends_on:
      - mariadb_nextcloud
    environment:
      - MYSQL_PASSWORD=${MARIADB_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_NEXTCLOUD_DATABASE}
      - MYSQL_USER=${MARIADB_NEXTCLOUD_USER}
      - MYSQL_HOST=mariadb_nextcloud
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=${NEXTCLOUD_DATA_DIR}
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
    volumes:
      #- nextcloud_var_www_html:/var/www/html/
      #- nextcloud_var_www_html_custom_apps:/var/www/html/custom_apps/
      #- nextcloud_var_www_html_config:/var/www/html/config/
      #- nextcloud_var_www_html_themes:/var/www/html/themes/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/var/www/html/:/var/www/html/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/var/www/html/custom_apps/:/var/www/html/custom_apps/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/var/www/html/config/:/var/www/html/config/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/var/www/html/themes/:/var/www/html/themes/
      #- nextcloud_var_www_html_data:${NEXTCLOUD_DATA_DIR}
      - ${BIG_STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud${NEXTCLOUD_DATA_DIR}:${NEXTCLOUD_DATA_DIR}
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/var/backups/:/var/backups/
      #- ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/nextcloud/data/:/var/www/html/themes/
      #- /etc/letsencrypt:/etc/letsencrypt:ro
      - ${STORAGE_ROOT_PATH}/generic/certbot/etc/letsencrypt/:/etc/letsencrypt:ro
    #ports:
    #  - "80:80/tcp" # HTTP
    networks:
      net_srv_private:
        ipv4_address: ${NEXTCLOUD_DOCKER_NETWORK_SRV_PRIVATE_IPV4}
      net_backend:
        ipv4_address: ${NEXTCLOUD_DOCKER_NETWORK_BACKEND_IPV4}

# mariadb_nextcloud(service) ############################################
  mariadb_nextcloud:
    container_name: mariadb_nextcloud
    hostname: mariadb_nextcloud
    build:
      context: ${IMAGE_ROOT_PATH}/mariadb
    restart: always
    command:
      - --max_allowed_packet=512MB
      - --innodb_log_file_size=512M
      - --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      #DNS_SERVER_IPS: ${MARIADB_NEXTCLOUD_DNS_SERVER_IPS}
      #DNS_SERVER_DOMAIN: ${MARIADB_NEXTCLOUD_DNS_SERVER_DOMAIN}
      MYSQL_ROOT_PASSWORD: ${MARIADB_NEXTCLOUD_DATABASE_ROOT_PASS}
      MARIADB_DATABASE: ${MARIADB_NEXTCLOUD_DATABASE}
      MARIADB_USER: ${MARIADB_NEXTCLOUD_USER}
      MARIADB_PASSWORD: ${MARIADB_NEXTCLOUD_PASSWORD}
      #TZ: UTC
    volumes:
      #- mariadb_var_lib_mysql:/var/lib/mysql/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/mariadb_nextcloud/var/lib/mysql/:/var/lib/mysql/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/mariadb_nextcloud/var/backups/:/var/backups/
      - mariadb_nextcloud_root:/root/
      - mariadb_nextcloud_etc_supervisor:/etc/supervisor/
      - mariadb_nextcloud_usr_local_bin:/usr/local/bin/
      - mariadb_nextcloud_etc_mysql:/etc/mysql/
      - mariadb_nextcloud_var_log:/var/log/
      - mariadb_nextcloud_var_spool_cron:/var/spool/cron/
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "3306:3306" # PORT = 3306 , MySQL database
    networks:
      net_backend:
        ipv4_address: ${MARIADB_NEXTCLOUD_DOCKER_NETWORK_BACKEND_IPV4}
