#version: '3.6'

#######################################################
#####                    NETWORK                  #####
#######################################################
networks:

################# NETWORK TO PRIVATE SERVERS - BRIDGE TO NETWORK net_srv_public on border commposer ambient
  net_srv_private:
    name: border_net_srv_private # this line is necessary to make a bridge
    external: true # this line is necessary to make a bridge
    enable_ipv6: false
    driver: ${DOCKER_NETWORK_SRV_PRIVATE_DRIVER_MODE}
    internal: false
    driver_opts:
      #parent: ${DOCKER_NETWORK_SRV_PRIVATE_PARENT_INTERFACE}
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      #com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SRV_PRIVATE_SUBNET_IPV4}
          gateway: ${DOCKER_NETWORK_SRV_PRIVATE_GATEWAY_IPV4}



#######################################################
#####                   VOLUMES                   #####
#######################################################

volumes:

# mariadb_wordpress(volume) ############################################
  mariadb_wordpress_var_lib_mysql:
  mariadb_wordpress_root:
  mariadb_wordpress_etc_supervisor:
  mariadb_wordpress_usr_local_bin:
  mariadb_wordpress_etc_mysql:
  mariadb_wordpress_var_log:
  mariadb_wordpress_var_spool_cron:

# wordpress(volume) ############################################
  wordpress_root:
  wordpress_usr_local_bin:
  wordpress_etc_supervisor:
  wordpress_srv_config:
  wordpress_var_log:
  #wordpress_var_www:
  wordpress_etc_apache2:
  wordpress_var_spool_cron:

# apache(volume) ############################################
  apache_root:
  apache_usr_local_bin:
  apache_etc_supervisor:
  apache_srv_config:
  apache_var_log:
  apache_var_www:
  apache_etc_apache2:
  apache_var_spool_cron:
  apache_etc_letsencrypt:

# certbot(volume) ############################################
  certbot_etc_supervisor:
  certbot_srv_config:
  certbot_var_log:
  certbot_var_spool_cron:
  certbot_usr_local_bin:
  certbot_root:
  #wordpress_var_www:
  #certbot_etc_letsencrypt:

    
#######################################################
#####                   SERVICES                  #####
#######################################################

services:

# mariadb_wordpress(service) ############################################
  mariadb_wordpress:
    container_name: ${CLIENT_NAME}-mariadb
    hostname: ${CLIENT_NAME}-mariadb
    build:
      context: ${IMAGE_ROOT_PATH}/mariadb
    restart: always
    command:
      - --max_allowed_packet=512MB
      - --innodb_log_file_size=512M
    environment:
      #DNS_SERVER_IPS: ${MARIADB_WORDPRESS_DNS_SERVER_IPS}
      #DNS_SERVER_DOMAIN: ${MARIADB_WORDPRESS_DNS_SERVER_DOMAIN}
      MYSQL_ROOT_PASSWORD: ${MARIADB_WORDPRESS_DATABASE_ROOT_PASS}
      MARIADB_DATABASE: ${MARIADB_WORDPRESS_DATABASE}
      MARIADB_USER: ${MARIADB_WORDPRESS_USER}
      MARIADB_PASSWORD: ${MARIADB_WORDPRESS_PASSWORD}
      #TZ: UTC
    volumes:
      #- mariadb_var_lib_mysql:/var/lib/mysql/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/mariadb_wordpress/var/lib/mysql/:/var/lib/mysql/ ### importante
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/mariadb_wordpress/var/backups/:/var/backups/
      - mariadb_wordpress_root:/root/
      - mariadb_wordpress_etc_supervisor:/etc/supervisor/
      - mariadb_wordpress_usr_local_bin:/usr/local/bin/
      - mariadb_wordpress_etc_mysql:/etc/mysql/
      - mariadb_wordpress_var_log:/var/log/
      - mariadb_wordpress_var_spool_cron:/var/spool/cron/
        #- /etc/timezone:/etc/timezone:ro
        #- /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "3306:3306" # PORT = 3306 , MySQL database
    networks:
      net_srv_private:
        ipv4_address: ${MARIADB_WORDPRESS_DOCKER_NETWORK_SRV_PRIVATE_IPV4}


# wordpress(service) ############################################
  wordpress:
    container_name: ${CLIENT_NAME}-wordpress
    hostname: ${CLIENT_NAME}-wordpress
    build:
      context: ${IMAGE_ROOT_PATH}/wordpress
    depends_on:
      mariadb_wordpress:
        condition: service_healthy
    links:
      - mariadb_wordpress
    restart: always
    environment:
      #DNS_SERVER_IPS: ${WORDPRESS_DNS_SERVER_IPS}
      #DNS_SERVER_DOMAIN: ${WORDPRESS_DNS_SERVER_DOMAIN}
      FORCE_RECONFIG: false
      HEALTHCHECK_ENABLED: true
      SYSTEM_NAME: wordpress
      CLIENT_NAME: ${CLIENT_NAME}
      DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      DATABASE_CONFIG_MODE: ${WORDPRESS_DATABASE_CONFIG_MODE}
      DATABASE_ADMIN_USER: ${WORDPRESS_DATABASE_ADMIN_USER}
      DATABASE_ADMIN_PASS: ${WORDPRESS_DATABASE_ADMIN_PASS}
      DATABASE_APP_USER: ${WORDPRESS_DATABASE_WORDPRESS_USER}
      DATABASE_APP_PASS: ${WORDPRESS_DATABASE_WORDPRESS_PASS}
      DATABASE_SCHEMA_NAME: ${WORDPRESS_DATABASE_NAME_WORDPRESS}
      WP_PLUGINS: ${WORDPRESS_WP_PLUGINS}
      WP_THEMES: ${WORDPRESS_WP_THEMES}
      WP_SITE_URL: ${WORDPRESS_WP_SITE_URL}
      WP_SITE_TITLE: ${WORDPRESS_WP_SITE_TITLE}
      WP_SITE_ADMIN_USER: ${WORDPRESS_WP_SITE_ADMIN_USER}
      WP_SITE_ADMIN_PASS: ${WORDPRESS_WP_SITE_ADMIN_PASS}
      WP_SITE_ADMIN_EMAIL: ${WORDPRESS_WP_SITE_ADMIN_EMAIL} 
    volumes:
      - wordpress_root:/root/ # pouco importante, somente retencao de historico
      - wordpress_usr_local_bin:/usr/local/bin/ 
      - wordpress_etc_supervisor:/etc/supervisor/ # pouco importante, somente garantia dos inicializadores adequados
      - wordpress_srv_config:/srv/config/ # pouco importante, garantia de scrips de inicializacao corretos
      - wordpress_var_log:/var/log/
      #- wordpress_var_www:/var/www/ 
      - wordpress_var_spool_cron:/var/spool/cron/
      #- certbot_etc_letsencrypt:/etc/letsencrypt
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/wordpress/var/www/wordpress:/var/www/wordpress
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/wordpress/var/backups/:/var/backups/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "${CLIENT_NAME}.domain.tld ${CLIENT_NAME}:${WORDPRESS_DOCKER_NETWORK_SRV_PRIVATE_IPV4}"
      #- "${CLIENT_NAME}.domain.tld ${CLIENT_NAME}:${WORDPRESS_DOCKER_NETWORK_SRV_PRIVATE_IPV6}"
    #dns:
      #- ${DOMAIN_DNS_SERVER_HOST}
    #dns_search:
      #- ${FQDN}
    #ports:
      #- "9000:9000/tcp"   # PHP-FPM 9000/TCP
    networks:
      net_srv_private:
        ipv4_address: ${WORDPRESS_DOCKER_NETWORK_SRV_PRIVATE_IPV4}


# apache(service) ############################################
  apache:
    container_name: ${CLIENT_NAME}-apache
    hostname: ${CLIENT_NAME}-apache
    build:
      context: ${IMAGE_ROOT_PATH}/apache
    depends_on:
      mariadb_wordpress:
        condition: service_healthy
    links:
      - wordpress
    restart: always
    environment:
      #DNS_SERVER_IPS: ${WORDPRESS_DNS_SERVER_IPS}
      #DNS_SERVER_DOMAIN: ${WORDPRESS_DNS_SERVER_DOMAIN}
      FORCE_RECONFIG: false
      HEALTHCHECK_ENABLED: true
      SYSTEM_NAME: apache
      CLIENT_NAME: ${CLIENT_NAME}
      SITE_HTTP_PORT: ${APACHE_SITE_HTTP_PORT}
      SITE_HTTPS_PORT: ${APACHE_SITE_HTTPS_PORT}  
      SITE_SSL_ENABLED: ${APACHE_SITE_SSL_ENABLED}
      SITE_NAME: ${APACHE_SITE_NAME}
      SITE_DOMAIN: ${APACHE_SITE_DOMAIN}
    volumes:
      - apache_root:/root/ # pouco importante, somente retencao de historico
      - apache_usr_local_bin:/usr/local/bin/ 
      - apache_etc_supervisor:/etc/supervisor/ # pouco importante, somente garantia dos inicializadores adequados
      - apache_srv_config:/srv/config/ # pouco importante, garantia de scrips de inicializacao corretos
      - apache_var_log:/var/log/
      #- apache_var_www:/var/www/
      - apache_etc_apache2:/etc/apache2/
      - apache_var_spool_cron:/var/spool/cron/
      #- apache_etc_letsencrypt:/etc/letsencrypt
      - ${STORAGE_ROOT_PATH}/generic/certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/webserber/etc/apache2/sites-enabled/:/etc/apache2/sites-enabled/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/webserber/etc/apache2/sites-available/:/etc/apache2/sites-available/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/wordpress/var/www/wordpress/:/var/www/wordpress/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/apache/var/backups/:/var/backups/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "${APACHE_SITE_NAME}.domain.tld ${APACHE_SITE_NAME}:${APACHE_DOCKER_NETWORK_SRV_PRIVATE_IPV4}"
      #- "${APACHE_SITE_NAME}.domain.tld ${APACHE_SITE_NAME}:${APACHE_DOCKER_NETWORK_SRV_PRIVATE_IPV6}"
    #dns:
      #- ${DOMAIN_DNS_SERVER_HOST}
    #dns_search:
      #- ${FQDN}
    #ports:
      #- "80:80/tcp"                                                              # APACHE_HTTP 80/TCP
      #- "${APACHE_SITE_HTTP_PORT}:${APACHE_SITE_HTTP_PORT}/tcp"       # APACHE_HTTP 80/TCP
      #- "443:443/tcp"                                                              # APACHE_HTTPS 443/TCP
      #- "${APACHE_SITE_HTTPS_PORT}:${APACHE_SITE_HTTPS_PORT}/tcp"     # APACHE_HTTPS 443/TCP
    networks:
      net_srv_private:
        ipv4_address: ${APACHE_DOCKER_NETWORK_SRV_PRIVATE_IPV4}


# certbot(service) ############################################
  certbot:
    container_name: ${CLIENT_NAME}-certbot
    hostname: ${CLIENT_NAME}-certbot
    build:
      context: ${IMAGE_ROOT_PATH}/certbot
    restart: always
    depends_on:
      - wordpress
    environment:
      CERTBOT_CERTIFICATE_TYPE: ${CERTBOT_CERTIFICATE_TYPE}
      CERTBOT_CERTIFICATE_PLUGIN: ${CERTBOT_CERTIFICATE_PLUGIN}
      CERTBOT_CERTIFICATE_SITE_NAME: ${CERTBOT_CERTIFICATE_SITE_NAME}
      CERTBOT_CERTIFICATE_SITE_DOMAIN: ${CERTBOT_CERTIFICATE_SITE_DOMAIN}
      CERTBOT_CERTIFICATE_EMAIL: ${CERTBOT_CERTIFICATE_EMAIL}
      CERTBOT_CERTIFICATE_WEBROOT: ${CERTBOT_CERTIFICATE_WEBROOT}
      CERTBOT_CERTIFICATE_API_TOKEN: ${CERTBOT_CERTIFICATE_API_TOKEN} 
    volumes:
      - certbot_etc_supervisor:/etc/supervisor/
      - certbot_srv_config:/srv/config
      - certbot_var_log:/var/log
      - certbot_var_spool_cron:/var/spool/cron
      - certbot_usr_local_bin:/usr/local/bin
      - certbot_root:/root
      #- wordpress_var_www:/var/www/
      - ${STORAGE_ROOT_PATH}/${CONTEXT_NAME}/wordpress/var/www/:/var/www/
      - ${STORAGE_ROOT_PATH}/generic/certbot/etc/letsencrypt/:/etc/letsencrypt/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      net_srv_private:
        ipv4_address: ${CERTBOT_DOCKER_NETWORK_SRV_PRIVATE_IPV4}

